// Copyright 2025 TikTok Inc.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
package com.tiktok.sparkling.method.media.choosemedia

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */

abstract class AbsChooseMediaMethodIDL : AbsSparklingIDLMethod<AbsChooseMediaMethodIDL.ChooseMediaInputModel, AbsChooseMediaMethodIDL.ChooseMediaResultModel>() {
    @IDLMethodName(name = "media.chooseMedia", params = ["maxCount", "mediaTypes", "sourceType", "cameraType", "compressImage", "saveToPhotoAlbum", "isNeedCut", "cropRatioWidth", "cropRatioHeight", "needBase64Data", "compressOption", "compressWidth", "compressHeight", "permissionDenyAction", "isMultiSelect", "useNewCompressSolution", "shouldKeepOriginalFormat", "compressQuality"], results = ["tempFiles"])
    final override val name: String = "media.chooseMedia"

    @IDLMethodParamModel
    interface ChooseMediaInputModel : IDLMethodBaseParamModel {
        companion object {
            const val ChooseMediaMediaTypesImage = "image"
            const val ChooseMediaMediaTypesVideo = "video"
            const val ChooseMediaSourceTypeAlbum = "album"
            const val ChooseMediaSourceTypeCamera = "camera"
            const val ChooseMediaCameraType = ""
            const val ChooseMediaCameraTypeBack = "back"
            const val ChooseMediaCameraTypeFront = "front"
            const val ChooseMediaCompressOption = 0
            const val ChooseMediaCompressOption1 = 1
            const val ChooseMediaCompressOption2 = 2
            const val ChooseMediaCompressOption3 = 3
            const val ChooseMediaCompressOption4 = 4
            const val ChooseMediaPermissionDenyAction = 0
            const val ChooseMediaPermissionDenyAction1 = 1
        }

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "maxCount", defaultValue = MethodParamDefaultValue(type = DefaultType.INT, intValue = 1))
        val maxCount: Number

        @get:IDLMethodStringEnum(ChooseMediaMediaTypesImage, ChooseMediaMediaTypesVideo)
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "mediaTypes", primitiveClassType = String::class, isEnum = true)
        val mediaTypes: List<String>

        @get:IDLMethodStringEnum(ChooseMediaSourceTypeAlbum, ChooseMediaSourceTypeCamera)
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "sourceType", isEnum = true)
        val sourceType: String

        @get:IDLMethodStringEnum(ChooseMediaCameraType, ChooseMediaCameraTypeBack, ChooseMediaCameraTypeFront)
        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "cameraType", isEnum = true, defaultValue = MethodParamDefaultValue(type = DefaultType.STRING, stringValue = ""))
        val cameraType: String

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "compressImage", defaultValue = MethodParamDefaultValue(type = DefaultType.BOOL, boolValue = false))
        val compressImage: Boolean

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "saveToPhotoAlbum", defaultValue = MethodParamDefaultValue(type = DefaultType.BOOL, boolValue = false))
        val saveToPhotoAlbum: Boolean

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "isNeedCut", defaultValue = MethodParamDefaultValue(type = DefaultType.BOOL, boolValue = false))
        val isNeedCut: Boolean

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "cropRatioWidth", defaultValue = MethodParamDefaultValue(type = DefaultType.INT, intValue = 0))
        val cropRatioWidth: Number

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "cropRatioHeight", defaultValue = MethodParamDefaultValue(type = DefaultType.INT, intValue = 0))
        val cropRatioHeight: Number

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "needBase64Data", defaultValue = MethodParamDefaultValue(type = DefaultType.BOOL, boolValue = false))
        val needBase64Data: Boolean

        @get:IDLMethodIntEnum(ChooseMediaCompressOption, ChooseMediaCompressOption1, ChooseMediaCompressOption2, ChooseMediaCompressOption3, ChooseMediaCompressOption4)
        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "compressOption", isEnum = true, defaultValue = MethodParamDefaultValue(type = DefaultType.INT, intValue = 0))
        val compressOption: Number

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "compressWidth", defaultValue = MethodParamDefaultValue(type = DefaultType.INT, intValue = 0))
        val compressWidth: Number

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "compressHeight", defaultValue = MethodParamDefaultValue(type = DefaultType.INT, intValue = 0))
        val compressHeight: Number

        @get:IDLMethodIntEnum(ChooseMediaPermissionDenyAction, ChooseMediaPermissionDenyAction1)
        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "permissionDenyAction", isEnum = true, defaultValue = MethodParamDefaultValue(type = DefaultType.INT, intValue = 0))
        val permissionDenyAction: Number

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "isMultiSelect", defaultValue = MethodParamDefaultValue(type = DefaultType.BOOL, boolValue = false))
        val isMultiSelect: Boolean

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "useNewCompressSolution", defaultValue = MethodParamDefaultValue(type = DefaultType.BOOL, boolValue = false))
        val useNewCompressSolution: Boolean

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "shouldKeepOriginalFormat")
        val shouldKeepOriginalFormat: Boolean?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "compressQuality", defaultValue = MethodParamDefaultValue(type = DefaultType.INT, intValue = 100))
        val compressQuality: Number
    }

    @IDLMethodResultModel
    interface ChooseMediaResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "tempFiles", nestedClassType = BridgeBeanChooseMediaTempFiles::class)
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "tempFiles", nestedClassType = BridgeBeanChooseMediaTempFiles::class)
        var tempFiles: List<BridgeBeanChooseMediaTempFiles>?
    }

    interface BridgeBeanChooseMediaTempFiles : IDLMethodBaseModel {
        companion object {
            const val ChooseMediaMediaTypeImage = "image"
            const val ChooseMediaMediaTypeVideo = "video"
        }

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "tempFilePath")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "tempFilePath")
        var tempFilePath: String?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "tempFileAbsolutePath")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "tempFileAbsolutePath")
        var tempFileAbsolutePath: String?

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "size")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "size")
        var size: Number? // you can't set a Number type to this param, only support Int/Double/Long/Float

        @get:IDLMethodStringEnum(ChooseMediaMediaTypeImage, ChooseMediaMediaTypeVideo)
        @set:IDLMethodStringEnum(ChooseMediaMediaTypeImage, ChooseMediaMediaTypeVideo)
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "mediaType", isEnum = true)
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "mediaType", isEnum = true)
        var mediaType: String?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "mimeType")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "mimeType")
        var mimeType: String?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "base64Data")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "base64Data")
        var base64Data: String?
    }
}
