// Generated by sparkling autolink
import Foundation

struct SparklingAutolinkModule {
    let name: String
    let iosModuleName: String?
    let className: String?
}

let sparklingAutolinkBundleId = "com.sparkling.playground"
let sparklingAutolinkModules: [SparklingAutolinkModule] = []
