// Generated by sparkling autolink
import Foundation

struct SparklingAutolinkModule {
    let name: String
    let iosModuleName: String?
    let className: String?
}

let sparklingAutolinkBundleId = "com.sparkling.app.SparklingGo"
let sparklingAutolinkModules: [SparklingAutolinkModule] = [
    SparklingAutolinkModule(name: "sparkling-navigation", iosModuleName: "Router", className: "RouterMethod")
]
