// Copyright 2025 TikTok Inc.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
package com.tiktok.sparkling.method.media.downloadfile

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */

abstract class AbsDownloadFileMethodIDL : AbsSparklingIDLMethod<AbsDownloadFileMethodIDL.DownloadFileInputModel, AbsDownloadFileMethodIDL.DownloadFileResultModel>() {
    @IDLMethodName(
        name = "media.downloadFile",
        params = ["url", "params", "header", "extension", "saveToAlbum", "needCommonParams", "timeoutInterval"],
        results = ["httpCode", "clientCode", "header", "filePath", "response"],
    )
    final override val name: String = "media.downloadFile"

    @IDLMethodParamModel
    interface DownloadFileInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "url")
        val url: String

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "params")
        val params: Map<String, Any>?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "header")
        val header: Map<String, Any>?

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "extension")
        val extension: String

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "saveToAlbum")
        val saveToAlbum: String?

        @get:IDLMethodParamField(
            required = false,
            isGetter = true,
            keyPath = "needCommonParams",
            defaultValue = MethodParamDefaultValue(type = DefaultType.BOOL, boolValue = true),
        )
        val needCommonParams: Boolean

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "timeoutInterval")
        val timeoutInterval: Number?
    }

    @IDLMethodResultModel
    interface DownloadFileResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "httpCode")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "httpCode")
        var httpCode: Number? // you can't set a Number type to this param, only support Int/Double/Long/Float

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "clientCode")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "clientCode")
        var clientCode: Number?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "header")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "header")
        var header: Map<String, Any>?

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "filePath")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "filePath")
        var filePath: String?

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "response")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "response")
        var response: Map<String, Any>?
    }
}
