// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
import '@testing-library/jest-dom'
import { expect, test, vi } from 'vitest'
import { render, getQueriesForElement } from '@lynx-js/react/testing-library'

import { App } from '../App.js'

test('App', async () => {
  const cb = vi.fn()

  render(
    <App
      onMounted={() => {
        cb(`__MAIN_THREAD__: ${__MAIN_THREAD__}`)
      }}
    />,
  )
  expect(cb).toBeCalledTimes(1)
  expect(cb.mock.calls).toMatchInlineSnapshot(`
    [
      [
        "__MAIN_THREAD__: false",
      ],
    ]
  `)
  expect(elementTree.root).toMatchInlineSnapshot(`
    <page>
      <view
        class=""
        style="box-sizing: border-box; width: 100%; padding-top: 0px; padding-bottom: 0px; flex: 1 1 0%;"
      >
        <view
          class="App"
        >
          <view
            class="Banner"
          >
            <view
              class="Logo"
            >
              <image
                class="Logo--lynx"
                src="/src/assets/sparkling_icon.png"
              />
            </view>
            <text
              class="Title"
            >
              TikTok Sparkling
            </text>
          </view>
          <view
            class="Content"
          >
            <view
              class="custom-list-container"
            >
              <scroll-view
                scroll-orientation="vertical"
                style="width:100%;height:240px"
              >
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        open
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        setStorage
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        getStorage
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        cardView
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        cardViewDemo
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        debugToolSwitch
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        mediaTest
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        themedColor
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        transStatusBar
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        chooseImage
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        chooseVideo
                      </text>
                    </view>
                  </wrapper>
                </view>
                <view
                  style="padding:10px"
                >
                  <wrapper>
                    <view
                      class="custom-button"
                    >
                      <text
                        style="color:#ffffff"
                      >
                        takePhoto
                      </text>
                    </view>
                  </wrapper>
                </view>
              </scroll-view>
            </view>
            <view
              class="input-card-url"
            >
              <text
                class="bold-text"
              >
                Bundle Path
              </text>
              <input
                class="input-box"
                placeholder="Enter bundle path (e.g. second.lynx.bundle)"
                text-color="#ffffff"
                value="second.lynx.bundle"
              />
            </view>
            <view
              class="expandable-list"
            >
              <view
                class="list-header"
              >
                <text>
                  Route Params 
                  <wrapper>
                    ▼
                  </wrapper>
                </text>
              </view>
              <wrapper />
            </view>
          </view>
        </view>
      </view>
    </page>
  `)
  const {
    findByText,
  } = getQueriesForElement(elementTree.root!)
  const element = await findByText('Bundle Path')
  expect(element).toBeInTheDocument()
  expect(element).toMatchInlineSnapshot(`
    <text
      class="bold-text"
    >
      Bundle Path
    </text>
  `)
})
