// Copyright 2025 TikTok Inc.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
package com.tiktok.sparkling.method.media.savedataurl

import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel

/**
 * GENERATED BY SPARKLING METHOD CLI.
 */

abstract class AbsSaveDataURLMethodIDL : AbsSparklingIDLMethod<AbsSaveDataURLMethodIDL.SaveDataURLInputModel, AbsSaveDataURLMethodIDL.SaveDataURLResultModel>() {
    @IDLMethodName(name = "media.saveDataURL", params = ["dataURL", "filename", "extension", "saveToAlbum"], results = ["filePath"])
    final override val name: String = "media.saveDataURL"

    @IDLMethodParamModel
    interface SaveDataURLInputModel : IDLMethodBaseParamModel {
        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "dataURL")
        val dataURL: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "filename")
        val filename: String

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "extension")
        val extension: String

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "saveToAlbum")
        val saveToAlbum: String?
    }

    @IDLMethodResultModel
    interface SaveDataURLResultModel : IDLMethodBaseResultModel {
        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "filePath")
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "filePath")
        var filePath: String?
    }
}
