// Copyright (c) 2025 TikTok Pte. Ltd.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
import type { AndroidDsl } from "./types";

export function androidManifestTemplate(packageName: string): string {
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    `<manifest package="${packageName}">`,
    '    <!-- Library manifest placeholder. Add <application> or <uses-permission> entries as needed. -->',
    '</manifest>',
    '',
  ].join('\n');
}

export function androidGradleTemplate(
  namespace: string,
  dsl: AndroidDsl
): string {
  return dsl === "kts" ? kotlinGradle(namespace) : groovyGradle(namespace);
}

function groovyGradle(namespace: string): string {
  return [
    'plugins {',
    "    id 'com.android.library'",
    "    id 'org.jetbrains.kotlin.android'",
    '}',
    '',
    'android {',
    `    namespace '${namespace}'`,
    '    compileSdk 34',
    '',
    '    defaultConfig {',
    '        minSdk 23',
    '    }',
    '}',
    '',
    '// Add dependencies required by your module.',
    '',
  ].join('\n');
}

function kotlinGradle(namespace: string): string {
  return [
    'plugins {',
    '    id("com.android.library")',
    '    id("org.jetbrains.kotlin.android")',
    '}',
    '',
    'android {',
    `    namespace = "${namespace}"`,
    '    compileSdk = 34',
    '',
    '    defaultConfig {',
    '        minSdk = 23',
    '    }',
    '}',
    '',
    '// Add dependencies required by your module.',
    '',
  ].join('\n');
}

export function iosPodspecTemplate(moduleId: string): string {
  return [
    'Pod::Spec.new do |s|',
    `  s.name             = 'Sparkling-${moduleId}'`,
    "  s.version          = '0.1.0'",
    `  s.summary          = '${moduleId} sparkling method module'`,
    "  s.description      = 'Generated by sparkling-method-cli init. Fill in details before publishing.'",
    `  s.homepage         = 'https://example.com/${moduleId}'`,
    "  s.license          = { :type => 'Apache-2.0' }",
    "  s.author           = { 'sparkling' => 'dev@example.com' }",
    "  s.source           = { :path => '.' }",
    "  s.platforms        = { :ios => '12.0' }",
    "  s.swift_version    = '5.0'",
    "  s.static_framework = true",
    '  s.pod_target_xcconfig = {',
    "    'DEFINES_MODULE' => 'YES',",
    "    'SWIFT_COMPILATION_MODE' => 'wholemodule'",
    '  }',
    "  s.default_subspec  = 'Core'",
    '',
    "  s.subspec 'Core' do |core|",
    "    core.source_files = 'Source/**/*.{h,m,mm,swift}'",
    '  end',
    '',
    "  s.test_spec 'Tests' do |tests|",
    '    tests.requires_app_host = false',
    "    tests.source_files = 'SparklingMethodTests/**/*.{h,m,mm,swift}'",
    '  end',
    '',
    "  s.dependency 'SparklingMethod/Core'",
    'end',
    '',
  ].join('\n');
}

export function iosUnitTestTemplate(moduleId: string): string {
  return [
    '// Copyright 2025 The Sparkling Authors. All rights reserved.',
    '// Licensed under the Apache License Version 2.0 that can be found in the',
    '// LICENSE file in the root directory of this source tree.',
    '',
    'import XCTest',
    `@testable import Sparkling_${moduleId}`,
    '',
    `final class SPK${moduleId}IndependentTests: XCTestCase {`,
    '    func testIndependentTestTargetBootstraps() {',
    '        XCTAssertNotNil(Bundle(for: type(of: self)))',
    '    }',
    '}',
    '',
  ].join('\n');
}
